### ISSUE TITLE
selenium-download breaking on node 6.

### ISSUE THREAD

**Issue by des-des** [dwyl/learn-nightwatch#24] opened 2016-07-03 13:21 UTC
There may be a problem with the module and nodev6: https://github.com/groupon/selenium-download/issues/19.

This may be a problem with node6 + ubuntu or something like that.. Ill investigate.

**Comment by nelsonic** [comment] 2016-07-03 13:58
Oh... 😕 
Thanks for investigating @des-des 👍

**Comment by ivarni** [comment] 2016-07-12 06:49
Can confirm this. Any progress looking into it or are more eyes needed?

**Comment by nelsonic** [comment] 2016-07-12 09:37
@ivarni if you have time to help investigate, please do!
I cloned the repo and started _trying_ to debug it: https://github.com/dwyl/selenium-download
(*invited you as contributor so we can colab on debugging it...*)
Enabled Travis-CI so we can track progress: https://travis-ci.org/dwyl/selenium-download/builds

**Comment by nelsonic** [comment] 2016-07-12 09:48
I _think_ that the issue is that the newer version of the [`download`](https://www.npmjs.com/package/download) has a breaking change ...

**Comment by ivarni** [comment] 2016-07-12 10:36
That sounds reasonable  given the wording of the error, the code is coffeescript which kinda put me off a bit but I'll try to find some time to have a look. Can't promise I'll get anywhere though.

**Comment by nelsonic** [comment] 2016-07-12 11:02
Yeah, coffeescript ... it should be quite familiar to you if you've been using ES6 (e.g arrow functions)
If you make _any_ progress, commit and push. thanks! 😉

**Comment by des-des** [comment] 2016-07-16 14:41
yeah had a look at this but have not got very far: dwyl/selenium-download#2

**Comment by des-des** [comment] 2016-07-16 14:41
also, tests seem to be failing whatever node version I am using

**Comment by nelsonic** [comment] 2016-07-16 18:43
The `download` module made breaking changes which mean the code in `selenium-download` does not work anymore (_with any version of node..._)
@des-des do you think we are better off crafting our own _clone_ of `selenium-download` in ES6 (_instead of CoffeeScript_) and side-stepping this issue...?

**Comment by des-des** [comment] 2016-07-16 18:47
:(

**Comment by ivarni** [comment] 2016-07-16 20:19
What the code in the `selenium-download` module does isn't overly complicated, it's the idea behind it that provides value. Rewriting it from scratch shouldn't be that much of a problem in my opinion and doing it in ES6 from the get-go might just make for a better end result than tinkering further with the ES6 code.

**Comment by ivarni** [comment] 2016-07-17 10:05
As a heads-up, I've already started working on a new module and got downloading the selenium jar working. I'm currently working on getting and unzipping the chromedriver. I've made a separate repo for it for the time being since I don't know if groupon will want a PR such a rewrite but if they do they're quite welcome to it. If not I suppose I'll just publish it. We're using the `selenium-download` in a project I'm on and it's blocking us from going to v6 and I need to fix that one way or the other.

**Comment by ivarni** [comment] 2016-07-17 14:35
So I've got `learn-nightwatch` running using an npm linked version of https://github.com/ivarni/get-selenium but it's still pretty rough around the edges (I've not tested much in the way of error handling yet and `update` and `forceUpdate` from the original `selenium-download` module is not implemented).

Still, it's progress. I think the brunt of the work is done unless I've overseen something (like `export default` not playing nice with `require`). Or there is some kinda license problem with doing this. I've borrowed some of the inner workings pretty verbatim from the coffee code.

**Comment by ivarni** [comment] 2016-07-20 06:45
@nelsonic I'd love an opinion on what to do here. Would publishing a new module that does the same as the existing `selenium-download` module be rude? We already have [download](https://www.npmjs.com/package/download) and [request](https://www.npmjs.com/package/request) which are pretty much interchangeable so it wouldn't be unheard of. 

I'm prepared to maintain such a module but I'm also prepared to hand it over to someone else, it doesn't really matter to me as I've achieved the thing that brought me here in the first place but since I did put some work into it it would be nice if that can help others as well.

**Comment by jkrems** [comment] 2016-07-27 02:13
FYI - it was pretty simple to [drop `download` and replace it with `request`](https://github.com/groupon/selenium-download/commit/861da4702118339bbe76bd7e73aaa8b69fd12370). The code is under BSD, so as long as you include attribution, you can do with it whatever you want. :)

**Comment by ivarni** [comment] 2016-08-04 15:29
@jkrems Great!

@nelsonic You can probably close this issue. There's no point updating `package.json` as the dependency is already `^2.0.2`. Anyone who already did a `npm install` should do `npm update` and anyone who does a fresh install will get the version that works.

**Comment by nelsonic** [comment] 2016-08-09 21:53
@jkrems  @ivarni thanks! ❤️

**Closed by nelsonic** 2016-08-09 21:53 UTC
Labels: bug, help wanted, question
